version: '3'
services:
  first:
    image: 'tomcat:9'
    ports:
      - "8080:8080"
    volumes:
      - "/mnt/wars:/usr/local/tomcat/webapps"
  second:
    image: 'tomcat:9'
    ports:
      - "80:8080"
    volumes:
      - "/mnt/wars:/usr/local/tomcat/webapps"


